### ISSUE TITLE
درخواست بررسی نتیجه کد پایتون و نحوه ادامه کار

### ISSUE THREAD

**Issue by anvaari** [ehsan957/mainwords#2]
سلام.
با وقفه زیاد من کار کد پایتون رو تموم کردم و توی [فورک](https://github.com/anvaari/mainwords) این ریپو موجوده.

این کد الان کل متن ها رو از ادرس ها جمع آوری میکنه و اون ها رو به کلمه تبدیل میکنه (قبلش نیم فاصله رو پاک میکنه) . و کلمه هایی که شرایط زیر رو دارن رو وارد دیکشنری اصلی میکنه و تعدادشون رو توی کل متن ها میشماره: 
- کلمه شامل علامت ها (کاما، نقطه و ...) نباشه 
-  عدد داخل کلمات نباشه (مثل ۳لام)

من فایل مروبوط به صد کلمه اول رو اینجا اپلود میکنم ولی 100 کلمه اولی که پیدا کردم با 100 کلمه شما متفاوته و دلیلش رو نمیدونم. اگه ممکنه مراحلی که برای این کار طی کردین رو بگین.
[Top100FarsiWords_py.txt](https://github.com/ehsan957/mainwords/files/7179329/Top100FarsiWords_py.txt)

و اینکه در ادامه به نظرتون چطور پیش بریم؟

**Comment by ehsan957** [comment]
<dir dir="rtl">

سلام محمد جان
اولا اینکه دمت گرم

من نیم‌فاصله‌ها را حفظ کردم، چون نیم‌فاصله را جزئی از نگارش فارسی امروز می‌دونم، مثلا می‌روم، می‌خوانم، می‌نویسم و صورت‌های جمعی مثل  آن‌ها و این‌ها را یک کلمه می‌تونیم درنظر بگیریم؛ احتمالا هم این اختلاف جزئی در پرتکرارترین‌ها به همین دلیله

من کار پیچیده‌ای نکردم اول با استفاده از  regex زیر به جز الفبای فارسی و عربی و فاصله و نیم‌فاصله مابقی را با فاصله جایگزین کردم
</dir>

`$txtcontent = preg_replace('/[^$\x{0620}-\x{064A}|\x{0671}-\x{06D1}|\x{200C}-\x{200D}]+/u', ' ', $txtcontent);`

<dir dir="rtl">

و بعد بیش از یک فاصله را با تک فاصله جایگزین کردم
</dir>

`$txtcontent = preg_replace('!\s+!', ' ', $txtcontent);`

<dir dir="rtl">
  
من حروف عربی را هم قبول کردم چرا که ما چندین ی چندین ک و همینطور چندین الف و همزه و ة در عربی داریم که ممکنه در نگارش فارسی هم بین فارسی زبان‌ها رایج باشه، ما دنبال پرتکرارترین‌ها هستیم و حتی باید غلط‌ها را هم ثبت کنیم. ما معلم دیکته نیستیم، مثلا راجب یک واژه‌ی غلط به تمام معناست که امروز رایج شده و بجای راجع به بکار میره اما ما ثبتش می‌کنیم

نقشه‌ی راه به نظر من یافتن پرکاربرترین‌ها در نگارش متداول بین سایر زبان‌ها باید باشه.

پروژه‌ات را اگر خواستی اصلاحش کن بعد همراه سورس کدت pull request بزن تا اضافه‌اش کنم به پروژه اصلی

</dir>

**Comment by anvaari** [comment]
سلام مجدد 
ممنونم بابت توضیحات کاملت، منم قبول دارم که نیم فاصله جزوی از نگارش امروزه ولی موضوع اینه که همه رعایت نمیکنن. و فکر کردم اگه یه رویه واحد باشه بهتره. اما هر کدوم یه مزایا و معایبی داره که فکر میکنم رویه ای که خودت در پیش گرفتی بهتر باشه.

باشه خیلی هم عالی من کد رو اصلاح میکنم و  pull request میزنم. امیدوارم تو ادامه ی پروژه هم موفق باشی:)
برای من تجربه خوبی بود.

**Comment by ehsan957** [comment]
<div dir="rtl">

ممنونم امیدوارم تو هم من را همراهی کنی

</div>

**Comment by anvaari** [comment]
من فکر کنم دیگه نیازی نباشه این ایشو باز باشه چون مرج انجام شد و این فاز تموم شد.
ممنونم امیدوارم موفق باشی
